### ISSUE TITLE
Search Bar

### ISSUE THREAD

**Issue by NeilPatel847** [owal7428/CSCI-3308-Group-5-Project#2]
Complete a functional search bar that allows the user to type keywords and enter them into a query

**Comment by StudentKyle** [comment]
Specifically, the user should be able to enter a city into the search bar, and be given relevant results (potentially based on other preferences) on travel locations, including weather and flight data.

**Comment by StudentKyle** [comment]
I am currently working on cleaning up user input on the existing search. Once this is done, the search bar should be complete.

**Comment by StudentKyle** [comment]
Completed and merged in #54
