### ISSUE TITLE
Logout Endpoint

### ISSUE THREAD

**Issue by zane-perry** [owal7428/CSCI-3308-Group-5-Project#20]
Capability for the user to log out of a user's session when logged in.

**Comment by StudentKyle** [comment]
Basic logout endpoint created in a21ffe6d6f55c444c5ae3898f7e4cbc67d0a9ca7 by Owen in #29.

**Comment by StudentKyle** [comment]
We could still add more features, such as only showing the logout button when the user is logged in if wanted, but this isn't strictly necessary.
