### ISSUE TITLE
Flight API

### ISSUE THREAD

**Issue by StudentKyle** [owal7428/CSCI-3308-Group-5-Project#6]
The user should be able to make basic searches for flight destinations and availability based on an external flight API.

**Comment by owal7428** [comment]
Flight API has been implemented in branch 17. Will be merged into master when full search results page is finished.

**Comment by StudentKyle** [comment]
See PR #53 
We don't want to have a hanging branch that stays unmerged until the full feature is done like you proposed in #6, because other PRs have made progress towards this other than this branch. Let's only make a PR for #17 once that is actually complete.

This issue should instead be closed when #53 is merged
